k3s_cluster:
  children:
    server:
      hosts:
        10.0.10.201:
    agent:
      hosts:
        10.0.10.202:
        10.0.10.203:

  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: proxmox
    k3s_version: v1.30.2+k3s1
    token: "changeme!"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

    extra_server_args: "--disable traefik --disable servicelb"
    
    k3s_post_install_tasks:
      - name: Install NGINX Ingress Controller
        kubernetes.core.helm:
          name: ingress-nginx
          chart_ref: ingress-nginx/ingress-nginx
          repo_url: https://kubernetes.github.io/ingress-nginx
          version: 4.8.3
          release_namespace: ingress-nginx
          create_namespace: true
          values:
            controller:
              service:
                type: LoadBalancer
              replicaCount: 2
              nodeSelector:
                ingress-ready: "true"
              tolerations:
                - key: "node-role.kubernetes.io/control-plane"
                  operator: "Exists"
                  effect: "NoSchedule"

    cluster_context: k3s-cluster